language: node_js
node_js:
  - 0.12
  - 4
  - 5
notifications:
  email:
    - lilleman@larvit.se
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script: mysql -e 'CREATE DATABASE test'
script: mocha test/test.js -confFile=db_travis.json
services:
  - mysql
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
#addons:
#  mariadb:
#    - 5.5
#    - 10.0
#    - 10.1
