language: node_js
node_js:
  - 0.12
  - 4
  - 5
notifications:
  email:
    - lilleman@larvit.se
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
before_script: mysql -e 'CREATE DATABASE test'
script: mocha test/test.js -confFile=db_travis.json
services:
  - mysql
#addons:
#  mariadb:
#    - 5.5
#    - 10.0
#    - 10.1
