language: node_js

node_js:
  - 8
  - 10
  - 11
  - 12

notifications:
  email:
    - lilleman@larvit.se
    - tobias@nublar.se

install:
  - npm i

before_script:
  - mysql -e 'CREATE DATABASE test'

script: npm test

addons:
  mariadb: 10.3
